### ISSUE TITLE
Relicensing request to MIT to all authors

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/gitops-stack#57]
Seems I have forgotten to add a license file when I started the git repo. The intended license as MIT.
Thus I'm asking for permission for all co-authors to re-license their contributions under the [MIT license](https://opensource.org/licenses/MIT).

Please just respond with a one line like "I approve relicensing my code to MIT".

Current status:

- [x] @Brutus5000 
- [x] @p4block 
- [x] @Sheikah45 
- [x] @fcaps 
- [x] @BlackYps

**Comment by Brutus5000** [comment]
I approve relicensing my code to MIT

**Comment by Sheikah45** [comment]
I approve relicensing my code to MIT

**Comment by BlackYps** [comment]
I approve relicensing my code to MIT

**Comment by p4block** [comment]
I approve relicensing my code to MIT

**Comment by fcaps** [comment]
Also approve it
